### ISSUE TITLE
weblogic域密码与节点密码（由于误删除了域密码、导致新建节点无法启动和密码重建）

### ISSUE THREAD

**Issue by WhyNotRunning** [WhyNotRunning/WhyNotRunning.github.io#36]
错误信息
`<Jul 17, 2017 2:08:18 PM CST> <Critical> <Security> <BEA-090403> <Authentication for user  denied>
<Jul 17, 2017 2:08:18 PM CST> <Critical> <WebLogicServer> <BEA-000386> <Server subsystem failed. Reason: weblogic.security.Secur
weblogic.security.SecurityInitializationException: Authentication for user  denied
	at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.doBootAuthorization(CommonSecurityServiceManagerDe
	at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.initialize(CommonSecurityServiceManagerDelegateImp
	at weblogic.security.service.SecurityServiceManager.initialize(SecurityServiceManager.java:888)
	at weblogic.security.SecurityService.start(SecurityService.java:141)
	at weblogic.t3.srvr.SubsystemRequest.run(SubsystemRequest.java:64)
	Truncated. see log file for complete stacktrace
Caused By: javax.security.auth.login.FailedLoginException: [Security:090304]Authentication Failed: User  javax.security.auth.log
	at weblogic.security.providers.authentication.LDAPAtnLoginModuleImpl.login(LDAPAtnLoginModuleImpl.java:261)
	at com.bea.common.security.internal.service.LoginModuleWrapper$1.run(LoginModuleWrapper.java:110)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.bea.common.security.internal.service.LoginModuleWrapper.login(LoginModuleWrapper.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	Truncated. see log file for complete stacktrace
`
解决：
还原误删除的域密码文件：
/Oracle/Middleware/user_projects/domains/base_domain/boot.properties
修改或删除控制台节点密码文件：
/Oracle/Middleware/user_projects/domains/base_domain/servers/AdminServer/security/boot.properties
删除旧的控制台节点权限文件夹的内容：
/Oracle/Middleware/user_projects/domains/base_domain/servers/AdminServer/data/ldap

**Comment by WhyNotRunning** [comment]
# weblogic使用root用户登录切换普通用户无法启动
weblogic报java.lang.ClassCastException:com.octetstring.vde.backend.BackendRoot之解决

如果在启动weblogic的时候忘记切换用户用root启动一次后，再次用weblogic启动，就会出现如下错误： 

<Aug 7, 2008 3:19:24 PM CST> <Critical> <EmbeddedLDAP> <BEA-171522> <An error occurred while initializing the Embedded LDAP Server. The exception thown is java.lang.ClassCastException: com.octetstring.vde.backend.BackendRoot. This may indicate a problem with the data files for the Embedded LDAP Server. If the problem is with the data files and it can not be corrected, backups of previous versions of the data files exist in ./servers/AdminServer/data/ldap/backup.> 
<Aug 7, 2008 3:19:24 PM CST> <Critical> <WebLogicServer> <BEA-000362> <Server failed. Reason: 

There are 1 nested errors: 

java.lang.ClassCastException: com.octetstring.vde.backend.BackendRoot 
        at weblogic.ldap.EmbeddedLDAP.start(EmbeddedLDAP.java:273) 
        at weblogic.t3.srvr.SubsystemRequest.run(SubsystemRequest.java:64) 
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:209) 
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:181) 

上面的错误原因主要是在用root用户启动weblogic的时候会在base_domain里产生root权限的文件，或者用root权限的文件覆盖了原来存在的weblogic所属文件，当再次切换到weblogic用户后，启动的时候就会出现权限问题，所以报告上面的错误。 
解决办法：
sudo chown -R weblogic:weblogic ./base_domain
